context("Given records,", function()
  local records = require("nd.records")
  local entry_log = require("nd.entry_log")
  describe("when they are directly created via entries, they", function()
    local entry = entry_log.Entry.from_str("2024-02-28 11:00 - !project: description @context")
    local record = records.Record:new(entry, 5)
    it("should behave like normal entries", function()
      assert.are.equal("context", record.context)
      assert.are.equal(28, record.timestamp:getday())
      assert.are.equal(11, record.timestamp:gethours())
      assert.are.same({}, record.tags)
      assert.are.equal(5, record.duration)
    end)
  end)

  describe("when they are updating their duractions, they", function()
    local entry1 = entry_log.Entry.from_str("2024-02-28 11:00 !project: description @context")
    local entry2 = entry_log.Entry.from_str("2024-02-28 12:30 other")
    local record = records.Record:new(entry2)
    record:update_duration_since(entry1)
    it("should use the correct timespan", function()
      assert.are.equal(90, record.duration)
    end)
  end)
end)
